"""empty message

Revision ID: 996f76cf161f
Revises: 
Create Date: 2023-10-17 19:54:11.776531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996f76cf161f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('color_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('command',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('device',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('binding_command',
    sa.Column('binding_id', sa.String(), nullable=False),
    sa.Column('command_id', sa.String(), nullable=False),
    sa.Column('primary_device', sa.String(), nullable=False),
    sa.Column('primary_key', sa.String(), nullable=False),
    sa.Column('primary_modifier', sa.String(), nullable=True),
    sa.Column('secondary_device', sa.String(), nullable=True),
    sa.Column('secondary_key', sa.String(), nullable=True),
    sa.Column('secondary_modifier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['binding.label'], ),
    sa.ForeignKeyConstraint(['command_id'], ['command.label'], ),
    sa.PrimaryKeyConstraint('binding_id', 'command_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binding_command')
    op.drop_table('device')
    op.drop_table('command')
    op.drop_table('binding')
    # ### end Alembic commands ###
